[[Resources]]
    Name = "yunpian"
    TimeOut = 1500 # ms
    Retry = 2 # 请求失败后的重试次数
    Protocol = "https" # 数据头协议, http / https / grpc / dubbogo
    Converter = "json"  # 数据体格式, form / raw / json
[[Resources.Interface]]
    Name = "BatchSend"
    Url = ""
    Method = "POST"
    Host = "sms.yunpian.com/v2/sms/tpl_batch_send.json"
    Port = "443"