#discardMsgIds = []
#
#[deduplicationRule.deduplication_10]
#    num = 1
#    time = 300
#[deduplicationRule.deduplication_20]
#    num = 5

msgTypeSmsConfig = [{"message_type_10":[{"weights":99,"scriptName":"TencentSmsScript"},{"weights":1,"scriptName":"YunPianSmsScript"}]},{"message_type_20":[{"weights":99,"scriptName":"TencentSmsScript"},{"weights":1,"scriptName":"YunPianSmsScript"}]},{"message_type_30":[{"weights":20,"scriptName":"TencentSmsScript"}]},{"message_type_40":[{"weights":20,"scriptName":"TencentSmsScript"}]},{"message_type_50":[{"weights":20,"scriptName":"LinTongSmsScript"}]}]
#[[msgTypeSmsConfig]]
#[[msgTypeSmsConfig.message_type_10]]
#    weights = 99
#    scriptName = "TencentSmsScript"
#[[msgTypeSmsConfig.message_type_10]]
#    weights = 1
#    scriptName = "YunPianSmsScript"
#[[msgTypeSmsConfig]]
#[[msgTypeSmsConfig.message_type_20]]
#    weights = 99
#    scriptName = "TencentSmsScript"
#[[msgTypeSmsConfig.message_type_20]]
#    weights = 1
#    scriptName = "YunPianSmsScript"
#[[msgTypeSmsConfig]]
#[[msgTypeSmsConfig.message_type_30]]
#    weights = 20
#    scriptName = "TencentSmsScript"
#[[msgTypeSmsConfig]]
#[[msgTypeSmsConfig.message_type_40]]
#    weights = 20
#    scriptName = "TencentSmsScript"
#[[msgTypeSmsConfig]]
#[[msgTypeSmsConfig.message_type_50]]
#    weights = 20
#    scriptName = "LinTongSmsScript"
#
#[flowControl]
#    flow_control_40=1